package it.uniroma2.ispw.model.raccolta;

public enum CategorieRivista {
	SETTIMANALE,BISETTIMANALE,MENSILE,
	BIMESTRALE,TRIMESTRALE,ANNUALE,
	ESTIVO,INVERNALE,SPORTIVO,CINEMATOGRAFICA,
	GOSSIP,TELEVISIVO,MILITARE,INFORMATICA

}
